"use client"

import { motion } from "framer-motion"
import {
  ArrowLeft,
  Brain,
  Hash,
  Binary,
  Zap,
  ShieldAlert,
  AlertTriangle,
  FlaskConical,
  BarChart2,
  CheckCircle,
} from "lucide-react"
import { AIChatbox } from "@/components/dashboard/ai-chatbox"
import { DashboardPageHeader } from "@/components/dashboard/page-header"

const sections = [
  {
    icon: AlertTriangle,
    color: "text-orange-500",
    bg: "bg-orange-500/10",
    title: "What is a Domain Generation Algorithm (DGA)?",
    body: "A Domain Generation Algorithm is code embedded in malware that automatically generates hundreds or thousands of random-looking domain names (like xjqkwz.com or 3kq9pzmv.net). The malware tries each generated domain until it finds one that responds — this is the attacker's Command & Control (C2) server. This technique makes it nearly impossible to block malware just by maintaining a list of known bad domains, because new ones are generated constantly.",
  },
  {
    icon: ShieldAlert,
    color: "text-destructive",
    bg: "bg-destructive/10",
    title: "Why blocklists aren't enough",
    body: "Traditional security tools rely on threat feeds and blocklists — databases of known-bad domains. DGA malware defeats this approach because it generates thousands of fresh domains per day, and only one or two are ever actually used. By the time a domain appears on a blocklist, the attack may already be over. PhishGuard's DGA detector catches these domains the instant they're queried, even if they've never been seen before.",
  },
  {
    icon: Hash,
    color: "text-purple-500",
    bg: "bg-purple-500/10",
    title: "Shannon Entropy",
    body: "Entropy measures how 'random' or unpredictable the characters in a domain name are. Human-chosen domain names are designed to be memorable: they use real words, brand names, or pronounceable strings. DGA-generated domains have high entropy because the characters are pseudo-randomly distributed. We calculate Shannon entropy on the domain's character sequence — legitimate domains typically score below 3.5 bits, while DGA domains often exceed 4.0.",
  },
  {
    icon: BarChart2,
    color: "text-blue-500",
    bg: "bg-blue-500/10",
    title: "Bigram and N-gram Analysis",
    body: "Natural language — including domain names — follows statistical patterns. The probability of certain character pairs (bigrams) and triplets (trigrams) occurring together is well-studied. For example, 'th', 'er', 'in' are common English bigrams. DGA domains contain abnormal character sequences like 'xj', 'qk', 'zv' — pairs that are extremely rare in real words. Our model measures the log-probability of observed bigrams against a trained language model of legitimate domains.",
  },
  {
    icon: FlaskConical,
    color: "text-violet-500",
    bg: "bg-violet-500/10",
    title: "LSTM Neural Network",
    body: "A Long Short-Term Memory (LSTM) network processes domain names one character at a time, learning sequential dependencies between characters. The model is trained on millions of known clean domains (Alexa Top 1M, Common Crawl) and known DGA domains from malware reverse-engineering databases (DGA Archive). After training, the LSTM assigns a probability score representing how likely each character sequence is to have been generated by an algorithm.",
  },
  {
    icon: Brain,
    color: "text-purple-500",
    bg: "bg-purple-500/10",
    title: "1D CNN Complementary Model",
    body: "Alongside the LSTM, a 1D Convolutional Neural Network (CNN) captures local patterns and fixed-length features in the domain string. CNNs are excellent at detecting short character motifs regardless of their position in the string. The CNN and LSTM outputs are ensembled — combined into a final score — which reduces false positives while maintaining high recall for true DGA domains.",
  },
  {
    icon: Binary,
    color: "text-cyan-500",
    bg: "bg-cyan-500/10",
    title: "Feature Engineering",
    body: "Beyond deep learning, we extract handcrafted features that complement the neural networks: domain length (DGA domains tend to be 12-20 characters), consonant-to-vowel ratio (DGA strings are often consonant-heavy), digit ratio (many DGA families append random numbers), TLD reputation (DGA campaigns often use .xyz, .top, .club, .info), and Levenshtein distance from the nearest known legitimate domain.",
  },
  {
    icon: Zap,
    color: "text-amber-500",
    bg: "bg-amber-500/10",
    title: "Real-time Detection",
    body: "Because the LSTM + CNN ensemble operates on character-level input, inference takes under 5ms per domain. This means PhishGuard can analyze every DNS query in your network in real time — catching DGA communication before the malware ever reaches its C2 server. This is far faster than waiting for threat intel feeds to update.",
  },
]

const metrics = [
  { label: "Detection Accuracy", value: "98.7%", desc: "Against known DGA families" },
  { label: "False Positive Rate", value: "0.3%", desc: "Legitimate domains misclassified" },
  { label: "Inference Speed", value: "<5ms", desc: "Per domain classification" },
  { label: "DGA Families", value: "50+", desc: "Supported in training set" },
]

export default function DGAHowItWorksPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="noise-overlay pointer-events-none fixed inset-0 z-50" />
      <DashboardPageHeader title="DGA Detector — How it Works" />

      <main className="mx-auto max-w-3xl px-6 py-12">
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-10"
        >
          <div className="mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-purple-500/10">
            <Brain className="h-7 w-7 text-purple-500" />
          </div>
          <h1 className="mb-3 text-3xl font-bold tracking-tight text-foreground">
            Domain Generation Algorithm Detection
          </h1>
          <p className="text-base leading-relaxed text-muted-foreground">
            Malware uses DGA to generate thousands of random domain names, making blocklists useless. PhishGuard uses an LSTM + 1D CNN ensemble trained on character-level data to detect these domains the instant they appear — before any threat feed has heard of them.
          </p>
        </motion.div>

        {/* Metrics */}
        <div className="mb-10 grid grid-cols-2 gap-3 sm:grid-cols-4">
          {metrics.map((m, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.06 }}
              className="rounded-xl border border-border bg-card/60 p-4 text-center"
            >
              <p className="text-xl font-bold text-foreground">{m.value}</p>
              <p className="mt-0.5 text-xs font-medium text-muted-foreground">{m.label}</p>
              <p className="mt-0.5 text-[11px] text-muted-foreground/60">{m.desc}</p>
            </motion.div>
          ))}
        </div>

        {/* How it works visually */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.15 }}
          className="mb-10 rounded-2xl border border-border bg-card/60 p-6"
        >
          <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-muted-foreground">
            Analysis Pipeline
          </h2>
          <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:gap-0">
            {[
              { label: "Domain Input", sub: "xjqkwz.com" },
              { label: "Character Tokenization", sub: "x·j·q·k·w·z" },
              { label: "LSTM Sequence Model", sub: "Sequential patterns" },
              { label: "1D CNN Motif Detector", sub: "Local char patterns" },
              { label: "Feature Ensemble", sub: "Entropy + bigrams + length" },
              { label: "DGA Score", sub: "0–100% confidence" },
            ].map((step, i, arr) => (
              <div key={i} className="flex items-center sm:flex-1">
                <div className="flex-1 rounded-lg border border-border bg-muted/30 px-2 py-2 text-center">
                  <p className="text-[11px] font-semibold text-foreground">{step.label}</p>
                  <p className="mt-0.5 font-mono text-[10px] text-muted-foreground">{step.sub}</p>
                </div>
                {i < arr.length - 1 && (
                  <div className="mx-1 hidden text-muted-foreground sm:block">→</div>
                )}
              </div>
            ))}
          </div>
        </motion.div>

        {/* Sections */}
        <div className="space-y-5">
          {sections.map((sec, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 + i * 0.05 }}
              className="rounded-xl border border-border bg-card/60 p-5"
            >
              <div className="mb-3 flex items-center gap-3">
                <div className={`flex h-9 w-9 items-center justify-center rounded-lg ${sec.bg}`}>
                  <sec.icon className={`h-4 w-4 ${sec.color}`} />
                </div>
                <h2 className="text-base font-semibold text-foreground">{sec.title}</h2>
              </div>
              <p className="text-sm leading-relaxed text-muted-foreground">{sec.body}</p>
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.7 }}
          className="mt-8 rounded-xl border border-primary/20 bg-primary/5 p-4"
        >
          <div className="mb-2 flex items-center gap-2">
            <CheckCircle className="h-4 w-4 text-primary" />
            <span className="text-sm font-semibold text-primary">When to use DGA Detection</span>
          </div>
          <p className="text-sm text-foreground/80">
            Use this feature when you encounter a domain that looks randomly generated — long strings of consonants, embedded numbers, or uncommon TLDs. It&apos;s especially useful for network defenders analysing DNS logs for infected machines trying to beacon out to C2 infrastructure.
          </p>
        </motion.div>
      </main>

      <AIChatbox context={{ feature: "dga_explainer" }} />
    </div>
  )
}
